version: '3.8'
services:
  github-rails-client:
    image: design-pickle/github-rails-client
    build: .
    container_name: github-rails-client
    command: rails s -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - PORT=3000
      - RAILS_ENV=development
