development:
  GITHUB_API_URL: https://api.github.com
  GITHUB_AUTH_TOKEN: 6682a2c358a3a43f82a7df89224c5b87c85f438d
test:
  GITHUB_API_URL: https://api.github.com
  GITHUB_AUTH_TOKEN: 6682a2c358a3a43f82a7df89224c5b87c85f438d
